---
- name: Install NGINX
  become: yes
  apt:
    name: nginx
    state: present

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd: unlink /etc/nginx/sites-enabled/default
  ignore_errors: yes

- name: Create NGINX Conf File For Flask
  become: yes
  template:
    src: "flask_proxy.conf.j2"
    dest: "/etc/nginx/sites-available/flask_proxy.conf"
    owner: "root"
    group: "root"
  notify: restart nginx

- name: Link NGINX Flask Reverse Proxy
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-available/flask_proxy.conf /etc/nginx/sites-enabled/flask_proxy.conf
  ignore_errors: yes

- name: Make Sure NGINX Service Is Running
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: config should not be worldwide read- or writeable
  file:
    path: "/etc/nginx"
    mode: "o-rw"
    owner: "root"
    group: "root"
    recurse: yes

- name: create additional configuration
  template:
    src: "hardening.conf.j2"
    dest: "/etc/nginx/conf.d/90.hardening.conf"
    owner: "root"
    group: "root"
  notify: restart nginx

- name: change configuration in main nginx.conf
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    regexp: '^\s*server_tokens'
    line: "    server_tokens {{ nginx_server_tokens }};"
    insertafter: "http {"
  notify: restart nginx

- name: change client_max_body_size in main nginx.conf
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    regexp: '^\s*client_max_body_size'
    line: "    client_max_body_size {{ nginx_client_max_body_size }};"
    insertafter: "http {"
  notify: restart nginx

- name: change client_body_buffer_size in main nginx.conf
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    regexp: '^\s*client_body_buffer_size'
    line: "    client_body_buffer_size {{ nginx_client_body_buffer_size }};"
    insertafter: "http {"
  notify: restart nginx

- name: change keepalive_timeout in main nginx.conf
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    regexp: '^\s*keepalive_timeout'
    line: "    keepalive_timeout {{ nginx_keepalive_timeout }};"
    insertafter: "http {"
  notify: restart nginx

- name: remove default.conf
  file:
    path: "{{ item }}"
    state: absent
  when: nginx_remove_default_site
  notify: restart nginx
  loop:
    - "/etc/nginx/conf.d/default.conf"
    - "/etc/nginx/sites-enabled/default"
