version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: deploy/before.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
      runas: root