---
- hosts: localhost
  vars:
    hostname: http://ec2-15-207-85-236.ap-south-1.compute.amazonaws.com:5000
    allow_ip: 10.10.10.10 #Specific ip allowed to internal
    endpoints:
      cached: /cached
      internal: /internal
      external: /external

  become: yes
  tasks:
    - name: Install NGINX From Apt-Get
      become: yes
      apt:
        name: nginx
        state: present

    - name: Disable NGINX Default Virtual Host
      become: yes
      command:
        cmd: unlink /etc/nginx/sites-enabled/default
      ignore_errors: yes

    - name: Create NGINX Conf File For Flask
      become: yes
      file:
        path: /etc/nginx/sites-available/flask_proxy.conf
        state: touch

    - name: Amend NGINX Conf File
      become: yes
      blockinfile:
        path: /etc/nginx/sites-available/flask_proxy.conf
        marker: ""
        block: |
          proxy_cache_path  /var/cache/cached levels=1 keys_zone=cached:10m;
          server {
            listen 80;
            location /internal {
              allow {{allow_ip}};
              deny all;
              proxy_pass {{ hostname }}{{ endpoints.internal }};
            }

            location /cached {
              proxy_cache cached;
              proxy_cache_use_stale updating;
              proxy_cache_lock on;
              proxy_cache_valid any 30s;
              proxy_pass {{ hostname }}{{ endpoints.cached }};
            }
            location /external {
              proxy_pass {{ hostname }}{{ endpoints.external }};
            }
          }

    - name: Link NGINX Flask Reverse Proxy
      become: yes
      command:
        cmd: ln -s /etc/nginx/sites-available/flask_proxy.conf /etc/nginx/sites-enabled/flask_proxy.conf
      ignore_errors: yes

    - name: Make Sure NGINX Service Is Running
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes
