---
- hosts: all
  become: yes
  tasks:
  - name: Install NGINX From Apt-Get
    become: yes
    apt:
      name: nginx
      state: present

  - name: Disable NGINX Default Virtual Host
    become: yes
    command:
      cmd: unlink /etc/nginx/sites-enabled/default

  - name: Create NGINX Conf File For Flask
    become: yes
    file:
      path: /etc/nginx/sites-available/flask_proxy.conf
      state: touch

  - name: Amend NGINX Conf File
    become: yes
    blockinfile:
        path: /etc/nginx/sites-available/flask_proxy.conf
        marker: ""
        block: |
          server {
              listen 80;
              location / {
                  proxy_pass http://localhost:5000;
                  proxy_set_header Authorization "";
                  proxy_read_timeout 90s;
              }
          }

  - name: Link NGINX Flask Reverse Proxy
    become: yes
    command:
      cmd: ln -s /etc/nginx/sites-available/flask_proxy.conf /etc/nginx/sites-enabled/flask_proxy.conf

  - name: Make Sure NGINX Service Is Running
    become: yes
    service:
      name: nginx
      state: restarted
      enabled: yes