---
# Install system apt packages
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install pip3
      apt:
        name: python3-pip
        state: present

# Install the app
- hosts: localhost
  tasks:
    - name: Download Api file using get_url
      get_url:
        url: "https://slice-adershmanoj.s3.ap-south-1.amazonaws.com/api.py"
        dest: "{{playbook_dir}}"
    - name: install flask, gunicorn in a virtualenv
      pip:
        name: 
          - flask
          - gunicorn
        virtualenv: "{{playbook_dir}}/flaskenv"
        virtualenv_python: python3.6

# Run the App 
- hosts: localhost
  tasks:
    - name: Run the api script in background
      shell: gunicorn --bind 0.0.0.0:5000 api:app &
